import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";

/**
 * Creates an AI provider dynamically selecting available providers from env keys.
 * Priority: OpenAI > Groq > Gemini > Mistral
 * chatModel() returns the first available provider.
 * getAllChatModels() returns all providers in order for application-level fallback loops.
 */
export const createGoogleAiProvider = (apiKey?: string) => {
  const stripQuotes = (str: string): string => {
    let s = str.trim();
    if (s.startsWith('"') && s.endsWith('"')) {
      s = s.slice(1, -1);
    } else if (s.startsWith("'") && s.endsWith("'")) {
      s = s.slice(1, -1);
    }
    return s;
  };

  const geminiKey = stripQuotes(
    apiKey || process.env.GEMINI_API_KEY || process.env.LOVABLE_API_KEY || "",
  );
  const groqKey = stripQuotes(process.env.GROQ_API_KEY || "");
  const openaiKey = stripQuotes(process.env.OPENAI_API_KEY || "");
  const mistralKey = stripQuotes(process.env.MISTRAL_API_KEY || "");

  // ✅ FIXED: Key validation now explicitly accepts the newer "AQ" prefix keys generated by Google AI Studio
  const isValidGeminiKey = 
    geminiKey && 
    geminiKey.trim() !== "" && 
    (geminiKey.startsWith("AIza") || geminiKey.startsWith("AQ"));

  // Build a list of all active/configured providers based on environment variables
  const activeProviders: ("openai" | "groq" | "google" | "mistral")[] = [];
  if (openaiKey) activeProviders.push("openai");
  if (groqKey) activeProviders.push("groq");
  if (isValidGeminiKey) activeProviders.push("google");
  if (mistralKey) activeProviders.push("mistral");

  if (activeProviders.length === 0) {
    activeProviders.push("google"); // fallback default to Google Generative AI
  }

  const instantiatedProviders = activeProviders.map((providerName) => {
    if (providerName === "openai") {
      const openai = createOpenAICompatible({
        name: "openai",
        baseURL: "https://api.openai.com/v1",
        apiKey: openaiKey,
      });
      return {
        name: "openai" as const,
        chatModel: (modelId?: string) => {
          const cleanModelId =
            modelId && !modelId.includes("gemini") && !modelId.includes("google")
              ? modelId.replace(/^openai\//, "")
              : "gpt-4o-mini";
          return openai.chatModel(cleanModelId);
        },
      };
    }
    if (providerName === "groq") {
      const groq = createOpenAICompatible({
        name: "groq",
        baseURL: "https://api.groq.com/openai/v1",
        apiKey: groqKey,
      });
      return {
        name: "groq" as const,
        chatModel: (modelId?: string) => {
          const cleanModelId =
            modelId && !modelId.includes("gemini") && !modelId.includes("google")
              ? modelId.replace(/^groq\//, "")
              : "llama-3.3-70b-versatile";
          return groq.chatModel(cleanModelId);
        },
      };
    }
    if (providerName === "google") {
      const googleInstance = createGoogleGenerativeAI({ apiKey: geminiKey });
      return {
        name: "google" as const,
        chatModel: (modelId?: string) => {
          let cleanModelId = modelId ? modelId.replace(/^google\//, "") : "gemini-2.0-flash";
          if (
            cleanModelId === "gemini-1.5-flash" ||
            cleanModelId === "gemini-1.5-flash-latest" ||
            cleanModelId.includes("2.5-flash")
          ) {
            cleanModelId = "gemini-2.0-flash";
          }
          return googleInstance(cleanModelId);
        },
      };
    }
    // mistral
    const mistral = createOpenAICompatible({
      name: "mistral",
      baseURL: "https://api.mistral.ai/v1",
      apiKey: mistralKey,
    });
    return {
      name: "mistral" as const,
      chatModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("gemini") && !modelId.includes("google")
            ? modelId.replace(/^mistral\//, "")
            : "mistral-large-latest";
        return mistral.chatModel(cleanModelId);
      },
    };
  });

  return {
    chatModel: (modelId?: string) => {
      // Return the first (highest priority) available model directly — no proxy wrapper
      // Use getAllChatModels() for application-level fallback loops
      return instantiatedProviders[0].chatModel(modelId);
    },
    getAllChatModels: (modelId?: string) => {
      return instantiatedProviders.map((p) => p.chatModel(modelId));
    },
    textEmbeddingModel: (modelId?: string) => {
      // Priority routing for embeddings: OpenAI > Gemini > Mistral
      if (openaiKey) {
        const openai = createOpenAICompatible({
          name: "openai",
          baseURL: "https://api.openai.com/v1",
          apiKey: openaiKey,
        });
        return openai.textEmbeddingModel("text-embedding-3-small");
      }
      if (isValidGeminiKey) {
        const googleInstance = createGoogleGenerativeAI({ apiKey: geminiKey });
        return googleInstance.textEmbeddingModel("text-embedding-004");
      }
      if (mistralKey) {
        const mistral = createOpenAICompatible({
          name: "mistral",
          baseURL: "https://api.mistral.ai/v1",
          apiKey: mistralKey,
        });
        return mistral.textEmbeddingModel("mistral-embed");
      }
      // Ultimate fallback
      const googleInstance = createGoogleGenerativeAI({ apiKey: geminiKey });
      return googleInstance.textEmbeddingModel("text-embedding-004");
    },
  };
};

/**
 * @deprecated Use createGoogleAiProvider instead.
 */
export const createLovableAiGatewayProvider = createGoogleAiProvider;