import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";

/**
 * Creates an AI provider dynamically selecting OpenAI, Groq, or Google Gemini
 * depending on what environment keys are present.
 * Priority: OpenAI > Groq > Gemini
 * OpenAI has higher rate limits and is more reliable for production use.
 */
export const createGoogleAiProvider = (apiKey?: string) => {
  const stripQuotes = (str: string): string => {
    let s = str.trim();
    if (s.startsWith('"') && s.endsWith('"')) {
      s = s.slice(1, -1);
    } else if (s.startsWith("'") && s.endsWith("'")) {
      s = s.slice(1, -1);
    }
    return s;
  };

  const geminiKey = stripQuotes(
    apiKey || process.env.GEMINI_API_KEY || process.env.LOVABLE_API_KEY || "",
  );
  const groqKey = stripQuotes(process.env.GROQ_API_KEY || "");
  const openaiKey = stripQuotes(process.env.OPENAI_API_KEY || "");
  const mistralKey = stripQuotes(process.env.MISTRAL_API_KEY || "");

  // ✅ FIXED: Key validation now explicitly accepts the newer "AQ" prefix keys generated by Google AI Studio
  const isValidGeminiKey = 
    geminiKey && 
    geminiKey.trim() !== "" && 
    (geminiKey.startsWith("AIza") || geminiKey.startsWith("AQ"));

  // Priority Routing logic: OpenAI > Groq > Gemini > Mistral
  let activeProvider: "openai" | "groq" | "google" | "mistral";
  if (openaiKey) {
    activeProvider = "openai";
  } else if (groqKey) {
    activeProvider = "groq";
  } else if (isValidGeminiKey) {
    activeProvider = "google";
  } else if (mistralKey) {
    activeProvider = "mistral";
  } else {
    // No valid provider configured — defaults to openai so downstream SDK operations throw a clear config error
    activeProvider = "openai";
  }

  console.log(`[AI Gateway] Selected active provider: ${activeProvider}`);

  if (activeProvider === "openai") {
    const openai = createOpenAICompatible({
      name: "openai",
      baseURL: "https://api.openai.com/v1",
      apiKey: openaiKey,
    });
    return {
      chatModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("gemini") && !modelId.includes("google")
            ? modelId.replace(/^openai\//, "")
            : "gpt-4o-mini";
        console.log(`[AI Gateway] Using OpenAI chat model: ${cleanModelId}`);
        return openai.chatModel(cleanModelId);
      },
      textEmbeddingModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("google")
            ? modelId.replace(/^openai\//, "")
            : "text-embedding-3-small";
        return openai.textEmbeddingModel(cleanModelId);
      },
    };
  }

  if (activeProvider === "groq") {
    const groq = createOpenAICompatible({
      name: "groq",
      baseURL: "https://api.groq.com/openai/v1",
      apiKey: groqKey,
    });
    return {
      chatModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("gemini") && !modelId.includes("google")
            ? modelId.replace(/^groq\//, "")
            : "llama-3.3-70b-versatile";
        console.log(`[AI Gateway] Using Groq chat model: ${cleanModelId}`);
        return groq.chatModel(cleanModelId);
      },
      textEmbeddingModel: (modelId?: string) => {
        if (openaiKey) {
          const openai = createOpenAICompatible({
            name: "openai",
            baseURL: "https://api.openai.com/v1",
            apiKey: openaiKey,
          });
          return openai.textEmbeddingModel("text-embedding-3-small");
        }
        if (isValidGeminiKey) {
          const googleInstance = createGoogleGenerativeAI({ apiKey: geminiKey });
          return googleInstance.textEmbeddingModel("text-embedding-004");
        }
        if (mistralKey) {
          const mistral = createOpenAICompatible({
            name: "mistral",
            baseURL: "https://api.mistral.ai/v1",
            apiKey: mistralKey,
          });
          return mistral.textEmbeddingModel("mistral-embed");
        }
        throw new Error(
          "No embedding provider available for Groq. Please configure OPENAI_API_KEY, GEMINI_API_KEY, or MISTRAL_API_KEY.",
        );
      },
    };
  }

  if (activeProvider === "mistral") {
    const mistral = createOpenAICompatible({
      name: "mistral",
      baseURL: "https://api.mistral.ai/v1",
      apiKey: mistralKey,
    });
    return {
      chatModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("gemini") && !modelId.includes("google")
            ? modelId.replace(/^mistral\//, "")
            : "mistral-large-latest";
        console.log(`[AI Gateway] Using Mistral chat model: ${cleanModelId}`);
        return mistral.chatModel(cleanModelId);
      },
      textEmbeddingModel: (modelId?: string) => {
        const cleanModelId =
          modelId && !modelId.includes("google")
            ? modelId.replace(/^mistral\//, "")
            : "mistral-embed";
        return mistral.textEmbeddingModel(cleanModelId);
      },
    };
  }

  // Default Fallback to Google Generative AI
  const googleInstance = createGoogleGenerativeAI({ apiKey: geminiKey });
  return {
    chatModel: (modelId?: string) => {
      let cleanModelId = modelId ? modelId.replace(/^google\//, "") : "gemini-2.0-flash";
      
      // Remap legacy versions to standard stable versions
      if (
        cleanModelId === "gemini-1.5-flash" ||
        cleanModelId === "gemini-1.5-flash-latest" ||
        cleanModelId.includes("2.5-flash")
      ) {
        cleanModelId = "gemini-2.0-flash";
      }
      console.log(`[AI Gateway] Using Google chat model: ${cleanModelId}`);
      
      // ✅ FIXED: Resolved TypeScript error ts(2339). 
      // The Google provider instance from @ai-sdk/google is an executable function, not an object containing a .chatModel method.
      return googleInstance(cleanModelId);
    },
    textEmbeddingModel: (modelId?: string) => {
      const cleanModelId = modelId ? modelId.replace(/^google\//, "") : "text-embedding-004";
      return googleInstance.textEmbeddingModel(cleanModelId);
    },
  };
};

/**
 * @deprecated Use createGoogleAiProvider instead.
 */
export const createLovableAiGatewayProvider = createGoogleAiProvider;