// Re-export the canonical document types so that files importing from this
// path continue to resolve correctly.
export type { DocumentModel, DocumentBlock } from "../types/document";

export type BlockType =
  | "heading"
  | "paragraph"
  | "list"
  | "table"
  | "code"
  | "math"
  | "image"
  | "divider"
  | "definition"
  | "concept"
  | "formula"
  | "workedExample"
  | "summary"
  | "keyPoints"
  | "studyTip"
  | "commonMistake"
  | "question"
  | "practiceQuestion"
  | "exercise"
  | "quiz"
  | "hint"
  | "answer"
  | "diagram"
  | "graph"
  | "chart"
  | "reaction"
  | "equation"
  | "proof"
  | "theorem"
  | "terminal"
  | "json"
  | "timeline"
  | "comparison"
  | "flashcard"
  | "note"
  | "warning"
  | "important"
  | "citation"
  | "relatedTopic"
  | "followUp"
  | "accordion";
